version: '3.6'
services:
  postgres:
    image: mdillon/postgis:11
    restart: always
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=testingwithrentals
    ports:
      - "5434:5432"
    volumes:
      - ./migrations/sqls/01_create_tables.up.sql:/docker-entrypoint-initdb.d/01_create_tables.up.sql
      - ./migrations/sqls/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql